apiVersion: v1
kind: Service
metadata:
  name: property-service
  namespace: finsight-app
spec:
  ports:
    - port: 8001
      targetPort: 8001
      name: http
    - port: 9001
      targetPort: 9001
      name: grpc
  selector:
    app: property-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  namespace: finsight-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - name: property-service
          image: ghcr.io/cndss25/property-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: DB_NAME
              value: "property_service"
#            - name: DB_USER
#              value: "test"
#            - name: DB_PASSWORD
#              value: "test"
            - name: DB_HOST
              value: "mongodb"
            - name: DB_PORT
              value: "27017"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_EXCHANGE
              value: "FinSight"
            - name: RABBITMQ_ROUTING_KEYS_COLLECTION
              value: "properties_listed,rental_income,test"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-property
  namespace: finsight-app
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: property-service
                port:
                  number: 8001
            path: /api/property
            pathType: Prefix